# Generated by Django 3.2.7 on 2021-10-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_remove_vehicle_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='next_check',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
