# Generated by Django 3.2.7 on 2021-10-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_auto_20211009_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='reg_number',
            field=models.SlugField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_category',
            field=models.SlugField(choices=[('leka kola', 'leka kola'), ('bus', 'bus'), ('kamion', 'kamion')], max_length=100, null=True),
        ),
    ]
