# Generated by Django 3.2.7 on 2021-10-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_auto_20211009_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='status',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_category',
            field=models.CharField(choices=[('leka kola', 'leka kola'), ('bus', 'bus'), ('kamion', 'kamion')], max_length=100, null=True),
        ),
    ]
