# Generated by Django 3.2.7 on 2021-10-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_auto_20211009_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='client_telnumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
