# Generated by Django 3.2.7 on 2021-10-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_alter_inspection_client_telnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_category',
            field=models.CharField(choices=[('car', 'car'), ('truck', 'truck'), ('bus', 'bus')], max_length=100, null=True),
        ),
    ]
