# Generated by Django 3.2.7 on 2021-10-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0009_alter_vehicle_vehicle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
