# Generated by Django 3.2.7 on 2021-10-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0010_inspection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('Inspection Period Not Over', 'Inspection Period Not Over'), ('Customer Notified Successfully', 'Customer Notified Successfully'), ('Error Occurred Trying To Notify Customer', 'Error Occurred Trying To Notify Customer')], max_length=100, null=True),
        ),
    ]
