# Generated by Django 3.2.8 on 2021-10-12 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspection', '0011_alter_inspection_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='customer',
        ),
        migrations.AddField(
            model_name='inspection',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
