# Generated by Django 3.2.8 on 2021-10-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0015_auto_20211012_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
